services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
      - ./otel-output:/var/otel        # output files land here on host
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4318:4318"
      - "4317:4317"
      - "8889:8889"
    depends_on:
      - jaeger

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "4319:4317"

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
