services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.119.0
    volumes:
      - ./otel-collector-config.yaml:/etc/otel/config.yaml
      - ./otel-output:/var/otel        # output files land here on host
    command: ["--config=/etc/otel/config.yaml"]
    ports:
      - "4318:4318"
      - "4317:4317"
      - "8889:8889"
    depends_on:
      - loki
      - tempo

  loki:
    image: grafana/loki:latest
    user: "0"
    ports:
      - "3100:3100"
    volumes:
      - ./loki.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml

  tempo:
    image: grafana/tempo:latest
    ports:
      - "3200:3200"
      - "4319:4317"
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command: -config.file=/etc/tempo.yaml

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--enable-feature=exemplar-storage"
    ports:
      - "9090:9090"
    depends_on:
      - otel-collector
  
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - loki
      - tempo
      - prometheus
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment: 
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
