receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"
#    default_labels_enabled:
#      exporter: false
#      job: true
#  otlp/loki:
#    endpoint: "http://loki:3100/otlp/v1/logs"
#    tls:
#      insecure: true
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true

  prometheus:
    endpoint: "0.0.0.0:8889"

  otlphttp/loki:
    endpoint: "http://loki:3100/otlp"
    tls:
      insecure: true

processors:
  batch:
    send_batch_size: 1
    timeout: 5s

  tail_sampling:
    decision_wait: 1s
    num_traces: 5
    expected_new_traces_per_sec: 1
    policies:
      - name: normal-traces
        type: probabilistic
        probabilistic:
          sampling_percentage: 10

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling, batch]
      exporters: [otlp/tempo]

    metrics:
      receivers: [otlp]
      exporters: [prometheus]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlphttp/loki]
