receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

exporters:
#  loki:
#    endpoint: "http://loki:3100/loki/api/v1/push"
#    default_labels_enabled:
#      exporter: false
#      job: true
#  otlp/loki:
#    endpoint: "http://loki:3100/otlp/v1/logs"
#    tls:
#      insecure: true
  otlp/tempo:
    endpoint: "http://tempo:4317"
    tls:
      insecure: true
  prometheus:
    endpoint: "0.0.0.0:8889"
    
processors:
  tail_sampling:
    decision_wait: 10s
    num_traces: 100000
    expected_new_traces_per_sec: 100
    policies:
      - name: error-traces
        type: status_code
        status_codes: [ status_code: ["ERROR"] ]
      - name: slow-traces
        type: latency
        latency: {threshold_ms: 2000}
      - name: normal-traces
        type: probabilistic
        probabilistic: {sampling_percentage: 10}
service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [tail_sampling]
      exporters: [otlp/tempo] #fanning out to both exporter
    metrics:
      receivers: [otlp]
      exporters: [prometheus]
#    logs:
#      receivers: [otlp]
#      exporters: [otlp/loki]